# Generated by Django 5.1 on 2024-09-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salida', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registros',
            new_name='RegistrosSalidas',
        ),
    ]
