# Generated by Django 5.1 on 2024-09-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registros',
            new_name='RegistrosSalidas',
        ),
    ]
